### ISSUE TITLE
Trigger out via low-level command

### ISSUE THREAD

**Issue by MaxP92** [mcleung/PyAPT#10]
Very useful code !

I'm trying to use an OUT trigger from a motor (XY stage MLS203, controlled by BBD202 precisely) to trig a display.
In the manual of the controller BBD202 (5.3.4 section page 53), , it says that I must use the "LLSetGetDigOPs" method, which I cannot find in the APT.dll

It seems to be a low-level method : do you know how I can use it ? Do I have to use the RS232 connection, if so what are the commands to communicate ?

(also, I tried with APT user, but even when I select "persist to hardware" the trigger seems to be the same when I move the stage, i.e. a TTL output of a certain width even if I change the mode from "Max vel. reached" to "Motion complete" for instance)

Thanks !

**Comment by mcleu** [comment]
Have you tried it with the newest dll?
You can get it from Thorlabs directly, or someone had uploaded it in #9 .

Once I test #9 I will merge it into the main branch.

**Comment by MaxP92** [comment]
I just tried it, this newest DLL does not contains new nethods, so "LLSetGetDigOPs" is still missing, unfortunately

**Comment by MaxP92** [comment]
just to keep you informed I managed to do what I want.

A virtual COM port must be created, and the low-level commands :
[link](https://www.thorlabs.com/Software/Motion Control/APT_Communications_Protocol.pdf)
can be used.
 The LLSetGetDigOPs equivalent method can be found on page 103

One can use PySerial with the newly created port, and type e.g. myMotor.write(b'\x10\x02\x01\x01\x21\x01') to enable channel 1

The two first bytes are for the message ID, the 2 after for the parameters (channel1, activate), the 5th for the destination (x21 for ch1 on slot card, or x50 for generic USB), the last for source (x01 for your computer)

EDIT : I put a portion of code on [my GitHub](https://github.com/MaxP92/thorlabs_python_low-level) if it can help anyone

**Comment by mcleu** [comment]
@MaxP92 If you think the changes would be helpful to others, feel free to make a change request back onto my branch.
