### ISSUE TITLE
Kinesis support?

### ISSUE THREAD

**Issue by dirtbirb** [mcleung/PyAPT#11]
I'm guessing this is outside the scope of this project, but I didn't see any closed issues on this, so: are there any plans to support [Kinesis](https://www.thorlabs.us/newgrouppage9.cfm?objectgroup_id=10285), or does anyone know of a Python project that does? The best I've found so far is [instrumental-lib](https://pypkg.com/pypi/instrumental-lib/), which has a basic implementation for one device.

I guess Thorlabs introduced Kinesis in 2016 and is using that for new devices. My impression is that Kinesis software will drive APT devices, but APT software won't drive Kinesis devices.

**Comment by mcleu** [comment]
Hi,
I'm not affiliated with Thorlabs, this was a project I did to help me out with my daily work that I thought may be useful to others.

Your best option would be to ask Thorlabs if they do plan to release an APT DLL that supports Kinesis. If so, then this could be adapted to include Kinesis in the future.

**Comment by dirtbirb** [comment]
Oh sorry, didn't mean to imply you were affiliated with Thorlabs, just wondering if you had any interest in expanding this yourself. There is a [Kinesis software package](https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=10285) available, but it's not documented well enough for a noob like me to know where to start. Even their example projects seem useless to me - they're all the same project, just with some GUI tweaks and a different name. 

Anyway, thanks for making this as it is, and thanks for the reply!
