### ISSUE TITLE
PyAPT.py calls self.config.get_pitch even though self.config is not defined

### ISSUE THREAD

**Issue by NotSoShaby** [mcleung/PyAPT#12]
In line 129 under the setStageAxisInformation() function variable pitch is set to equal `c_float(self.config.get_pitch())` and it falls on "self.config is not defined". indeed self.config is nowhere to be found in the code. Is there a way to bypass that/set the axis information. 
I'll keep looking for a way and update if i find something.

```
    def setStageAxisInformation(self, minimumPosition, maximumPosition):
        minimumPosition = c_float(minimumPosition)
        maximumPosition = c_float(maximumPosition)
        units = c_long(1) #units of mm
        # Get different pitches of lead screw for moving stages for different stages.
        **pitch = c_float(self.config.get_pitch())**
        self.aptdll.MOT_SetStageAxisInfo(self.SerialNum, minimumPosition, maximumPosition, units, pitch)
        return True
```

**Comment by mcleu** [comment]
You should be able to `getStageAxisInformation` for the pitch / min / max values, save that, and then you can pass those values back when using `setStageAxisInformation`

Let me know if you have any questions on how to implement it.
I can write a fix for it if needed.

**Comment by NotSoShaby** [comment]
I tried this and it didn't work. 
The reason is that `getStageAxisInformation ` method returns a list while the  `setStageAxisInformation ` expect to get two separate parameters - as you can see in the picture:
![image](https://user-images.githubusercontent.com/26500236/32780902-a32ccd6e-c94b-11e7-8402-e483e4f9319a.png)

Furthermore, if I use indexing on the list I received from the `getStageAxisInformation ` to pass the correct parameters to `setStageAxisInformation ` I still get the error that I got before because APTMotor doesn't have a config function or variable anywhere (that triggers the error).

My solution (although its not ideal) was to simply comment out that line and set the `pitch =  c_float(1) `  like this:
![image](https://user-images.githubusercontent.com/26500236/32780790-39295464-c94b-11e7-9756-010bffda8ef3.png)

I'm not quite sure what did I lose in terms of functionality (i'll be happy to hear if you know) but it works fine for what I needed this.

**Comment by NotSoShaby** [comment]
Worked out a solution. 
make the `setStageAxisInformation ` look like this:

```
    def setStageAxisInformation(self, stageAxisInformation):
        minimumPosition = c_float(stageAxisInformation[0])
        maximumPosition = c_float(stageAxisInformation[1])
        units = c_long(stageAxisInformation[2]) #units of mm
        # Get different pitches of lead screw for moving stages for different stages.
        pitch = c_float(stageAxisInformation[3])
        self.aptdll.MOT_SetStageAxisInfo(self.SerialNum, minimumPosition, maximumPosition, units, pitch)
        return True
```

Should get the job done. 
Worked for me.

**Comment by mcleu** [comment]
Implemented changes, thanks!
