### ISSUE TITLE
self.aptdll.APTInit() bug

### ISSUE THREAD

**Issue by ChangShuaibin** [mcleung/PyAPT#13]
Hi, I used the pyapt.py to control the stage, but when it ran through self.aptdll.APTInit() something was wrong, I couldn't figure out the reason. Can anyone help me? Thanks.

**Comment by mcleu** [comment]
Can you run the debug file? Which line does it get stuck on?
What's the error message you're getting?

**Comment by ChangShuaibin** [comment]
Hi, Michael,

Thanks for your reply. I've solved the problem. It turned out that your
shared dll file didn't apply to our stage. I downloaded the aptuser
software and used that dll file and the control of the stage was
successful. Thanks anyway!

Best,

Shuaibin

2018-01-06 4:04 GMT+08:00 Michael Leung <notifications@github.com>:

**Comment by mcleu** [comment]
Great! I am glad you sorted it out. Did the new .dll work with the PyAPT python code? Or did you need a new code?

**Comment by ChangShuaibin** [comment]
The code worked. It was great. Thanks.

2018-01-06 13:53 GMT+08:00 Michael Leung <notifications@github.com>:
