### ISSUE TITLE
tpz001?

### ISSUE THREAD

**Issue by JoosMax** [mcleung/PyAPT#14]
Thanks for the good work,

I was wandering it is possible to control a piezo cube controller TPZ001 with this wrapper?
Hardwaretype is 30. 
System Level Exports command as GetHWInfo or APTInit work fine but no Specific Exports for piezo controller seems to exist in the apt.dll or APTAPI.h

Maxime

**Comment by mcleu** [comment]
If it's not listed, then I do not beleive so.
You should check with Thorlabs to double check; maybe they can provide you an updated dll that will control the TPZ001.

**Comment by JoosMax** [comment]
Thank you Michael,
I posted a Feedback on Thorlabs website to know more about it.
I'll let you know about their answer.

Maxime

**Comment by JoosMax** [comment]
Ok, Thorlabs did not implement piezo command in the apt.dll.
Response from thorlabs : 
"For control [TPZ001] within Python, it may be best to control the device through a low level COM port via of our communications protocol (...)". (https://www.thorlabs.com/software_pages/ViewSoftwarePage.cfm?Code=Motion_Control)

So first step is to configure the usb port as virtual COM.
Then with the python package ftd2xx, you can communicate at low level.

Here is a basic example to set and read voltage on my piezo controller (TPZ001):

import ftd2xx
import ftd2xx.defines as constants
import time

serial = b"81864947" # serial number of device


#Recommended d2xx setup instructions from Thorlabs.
motor = ftd2xx.openEx(serial)
print(motor.getDeviceInfo())
motor.setBaudRate(115200)
motor.setDataCharacteristics(constants.BITS_8, constants.STOP_BITS_1, constants.PARITY_NONE)
time.sleep(.05)
motor.purge()
time.sleep(.05)
motor.resetDevice()
motor.setFlowControl(constants.FLOW_RTS_CTS, 0, 0)
motor.setRts()

#Set voltage / call the function MGMSG_PZ_SET_OUTPUTVOLTS
V = 10.00
volt_int = int(round((V)*32767/75.))
volt = ''.join(chr(x) for x in [0x43, 0x06, 0x04, 0x00, 0xD0, 0x01, 0x01, 0x00, volt_int%256, volt_int/256])
r = motor.write(volt)

#read voltage / call the function MGMSG_PZ_GET_OUTPUTVOLTS
com = b'\x44\x06\x01\x00\x01\x01'
r = motor.write(com)
time.sleep(0.1)
b = motor.getQueueStatus()
c = motor.read(b)
v_int = ord(c[9])*256+ord(c[8])
v_read = v_int*75./32767

#Close device
motor.close()

**Comment by mcleu** [comment]
Thanks. Looks like it's solved?
Can you please close the issue?
You should still be able to reference the issue even after it's closed.
