### ISSUE TITLE
Cannot move backwards

### ISSUE THREAD

**Issue by elevenert** [mcleung/PyAPT#18]
Hi,
I'm using two NRT100/M stages with controller BSC202 (1ch driver card is SCC001, hwtype = 21). 
I'm able to move my stage in the forward direction but it doesn't respond to any backwards moving commands including go_home. I tried different sets of home parameters but none of them helped.
I was wondering if you might know what I've missed to get it work?
Thanks.

**Comment by bhushansavalia** [comment]
Hi, I am using thor labs controller (APT BBD202). Can anybody please help me how do I find the hardware type of the controller and execute it in the python?

**Comment by mcleu** [comment]
Go home is a specific command only available on certain models. Do you have that functionality by default on the LabView interface?

**Comment by elevenert** [comment]
> Go home is a specific command only available on certain models. Do you have that functionality by default on the LabView interface?

Thanks for the reply. I've solved this. The problem was that I didn't run the APT Config utility before I tried to control the stages in Python.

**Comment by mcleu** [comment]
Thanks for the update. Anyhow, APT is being depricated by Thorlabs, in favor of Kinesis.
I suggest you merge to Kinesis with Instrumental package here: https://github.com/mabuchilab/Instrumental/
