### ISSUE TITLE
DLL not found

### ISSUE THREAD

**Issue by wwang2** [mcleung/PyAPT#4]
Hi! Michael 

First, thank you for developing this package. I was trying to run it after putting the dll and lib files in the same folder. I ran the following command

`from PyAPT import APTMotor`
`Motor1 = APTMotor(83861368, HWTYPE=31)`

and get error message like the following:
## `ERROR: DLL not found

WindowsError                              Traceback (most recent call last)
<ipython-input-7-a8c02469604f> in <module>()
      1 from PyAPT import APTMotor
      2 import time
----> 3 Motor1 = APTMotor(83861368, HWTYPE=31)

C:\Users\M-LAB\Desktop\TGS Python\pyAPT\PyAPT.py in **init**(self, SerialNum, HWTYPE, verbose)
     47         if not os.path.exists(dllname):
     48             print "ERROR: DLL not found"
---> 49         self.aptdll = windll.LoadLibrary(dllname)
     50         self.aptdll.EnableEventDlg(True)
     51         self.aptdll.APTInit()

C:\Anaconda2\lib\ctypes__init__.pyc in LoadLibrary(self, name)
    441 
    442     def LoadLibrary(self, name):
--> 443         return self._dlltype(name)
    444 
    445 cdll = LibraryLoader(CDLL)

C:\Anaconda2\lib\ctypes__init__.pyc in **init**(self, name, mode, handle, use_errno, use_last_error)
    363 
    364         if handle is None:
--> 365             self._handle = _dlopen(self._name, mode)
    366         else:
    367             self._handle = handle

WindowsError: [Error 126] The specified module could not be found`

I am pretty sure I put the dll in the same directory, do you have any idea what might be wrong?

Thank you

**Comment by mcleu** [comment]
Do your motor controllers work with Thorlabs provided packages? (eg LabView)

Do you have the ThorlabsAPT software installed?
It is obtainable from ThorLabs APT Software page - http://www.thorlabs.us/software_pages/ViewSoftwarePage.cfm?Code=APT

**Comment by wwang2** [comment]
Thank you for replying. Yes, I have been using the APT software. I haven't tried using LabView to control it, I have only controlled it from the software. 

I haven't tried the LabView package. 

Any other source of problems?

**Comment by wwang2** [comment]
sorry for bugging you again, I tried again today and I think I followed the right procedure:
Download the package and copy APT.dll, APT.lib and pyAPT.py to the same folder as the python script, still reproduced the same error. 

I also try to copy APT.dll and APT.lib to \Anaconda2\Dlls and \Libs. does not seem to help. I feel like I am missing some standard\essentail steps that a rookie like me may easily overlook. 

Would really appreciate further clarification.

Thank you

**Comment by mcleu** [comment]
I'm not sure what the problem can be. Maybe try contacting Thorlabs for an updated dll.

I noticed similar problems in the past with bit-version mismatch.

What version of windows are you using? 64 bit (x64) or 32 bit (x86)?
What version of Python are you running? 2.7? 3.5? What Python bit version are you running (64 bit or 32 bit)? Last; what version of the dll are you using (64 or 32 bit)?

Make sure the dll you use matches the Python bit version.

**Comment by wwang2** [comment]
Hi! Michael 

I found the problem, the default dll name in the source code is "APT86x.dll" instead of "APT.dll". I changed it and it worked.  It may be a little less obvious for people who know less in depth. Maybe include this in the README document?

**Comment by mcleu** [comment]
Thank you.
I changed the code to fix it.
See 102a9d03530c957eba58ab4e88a5694cd2659c29

**Comment by wwang2** [comment]
Thank you for your commitment on this project, this saves me a lot of time!
