### ISSUE TITLE
go_home function error

### ISSUE THREAD

**Issue by leviatanik** [mcleung/PyAPT#5]
I came across an error with the go_home() function. The problem is that when go_home() function is executed the program crashes with the following error message:

c:\PyAPT.pyc in go_home(self)
      292             raise Exception('Please connect first! Use initializeHardwareDevice')
      293         if self.verbose: print 'go_home SUCESS'
--> 294         self.aptdll.MOT_MoveHome(self.SerialNum)
      295         return True
      296

Any suggestion on how to solve this issue?

**Comment by mcleu** [comment]
What device are you using? Does it support the gohome (You can check with the Thorlabs provided module)
Can you enable verbose mode?
When you call APTMotor(), just add the option APTMotor(verbose=true)

From what I can tell, It seems it's not connected properly. (Line 292)

Can you try running [debug.py](http://github.com/mcleung/PyAPT/blob/master/debug.py) with your correct hardware number (See readme: HWTYPE) and the correct serial number; and then paste the output here?

**Comment by leviatanik** [comment]
I am using horizontal stage LTS300/M with built in controller and also LNR50S through APT Precision Motion Controller. Using ThorLabs software I can home both of the stages without any issues.

Here is the output of debug.py for both stages I am using:
1) LTS300/M
In [8]: run debug.py
DLL Loaded
0
SerialNo 0
45824327
['LTS300', 'SW Version 1.0.2', 'APT Stepper Motor Controller']

2) LNR50S
In [10]: run debug.py
DLL Loaded
0
SerialNo 0
90812692
SerialNo 1
90812693
SerialNo 2
90812694
['17BSC002\x10', 'SW Version 1.0.3', 'apt Stepper Controller']

**Comment by mcleu** [comment]
Which controller is not homing?
Are you able to connect and initialize them without error?
Are move commands working, just the go home that is not working?

Can you try this, and copy the output for me?
This will control the LTS300.

`Motor1 = APTMotor(45824327, HWTYPE=42,verbose=true) `
`print(Motor1.getPos())`
`Motor1.mRel(1)`
`Motor1.mRel(-1)`
`Motor1.goHome()`

I'm not sure if the LNR50S will work/is supported, it looks like it's coded in as a BSC002  [HWTYPE=13], so you can give that a shot.

**Comment by leviatanik** [comment]
Both controllers (LTS300/M and LNR50S) give the same error (that I described above) when executing go_home command.

I can connect to both stages without any problem. I can move them using either absolute or relative move commands. It's only the go_home command that causes everything to crash.

Here is the output for the LTS300/M:
```
Serial is 45824327
initializeHardwareDevice serial c_long(45824327)
initializeHardwareDevice connection SUCESS
getPos probing...
getPos  0.0
0.0
mRel  1 c_float(1.0)
mRel SUCESS
mRel  -1 c_float(-1.0)
mRel SUCESS
Going home
go_home SUCESS
-----------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
c:\halosat\debug2.py in <module>()
      5 Motor1.mRel(1)
      6 Motor1.mRel(-1)
----> 7 Motor1.go_home()
c:\halosat\PyAPT.pyc in go_home(self)
    292             raise Exception('Please connect first! Use initializeHardwareDevice')
    293         if self.verbose: print 'go_home SUCESS'
--> 294         self.aptdll.MOT_MoveHome(self.SerialNum)
    295         return True
    296
ValueError: Procedure probably called with not enough arguments (4 bytes missing)
```

It looks like all commands are executed with success, even the go_home. But then it just crashes.

**Comment by mcleu** [comment]
That's odd. I'm not sure what is wrong then.
It is crashing on 294, so it's something on the DLL side.
Have you tried to contact Thorlabs to see what they think?

The only thing I could see that may be causing the problem is if the controllers are dual channels, it doesn't know which channel to Home. (Also can been seen from the hint saying that it's missing 4 bytes.) I'm not sure how to make that change since it's all hidden behind the DLL layer.

**Comment by mcleu** [comment]
Have you been able to resolve the issue?
Have you made any progress on this?
