### ISSUE TITLE
Jog up/down function

### ISSUE THREAD

**Issue by danustc** [mcleung/PyAPT#6]
Hi Michael,  

Thanks for developing this Python wrapper for Thorlabs APT! I am trying to adapt it for a Thorlabs TDC 001 step motor in my instrument (I forked your repository using the account @huanglab-ucsf last week ). The moving functions worked very well, but I found that there is no jogging function, which is crucial for my experiment. I tried to add it by calling self.aptdll.MOT_MoveJog(self.SerialNum, c_int(<moving mode>)) but failed. It seems the library does have the MOT_MoveJog function, but I did not have the correct input. I was wondering if you have attempted to add a similar function and what arguments should be fed to it. Thanks! 

Best,
Dan

**Comment by mcleu** [comment]
Hi Dan,

What do you mean by "jog"? It is a short, controlled movement in one direction?

I have implemented the +1, +10, +100 buttons for that purpose.
I tried to replicate as much functionality from the default interface as I could.
Let me know if other features are missing.

**Comment by danustc** [comment]
Jog means move up or down by a tiny step. Each step motor should have a default step size upon initialization, but it can be changed. Thorlab's ActiveX control has jog buttons (see the sample picture there). Theoretically the "move relative" function can be wrapped into a jog function, but I was just wondering if we can directly call the function already in the library. 

Thanks for looking into this!

**Comment by mcleu** [comment]
Are the functionality provided with the +1, +10, +100 in the current GUI sufficient?
If not, I can investigate the option to add/use the MOT_MoveJog commands.

You are correct, those are implemented with the move relative (mRel) command, lines 133 to 162 of [myGUI.py](https://github.com/mcleung/PyAPT/blob/master/myGUI.py)

**Comment by danustc** [comment]
I may need arbitrary step sizes, so I wrote my own function based on the MOT_MoveRelativeEx. I will test it and keep you updated. If it works then you don't have to spend time digging other commands. Thanks!

**Comment by mcleu** [comment]
Hi Dan,
Has it resolved your problems? Can I close the issue?
Let me know!

**Comment by danustc** [comment]
Hi Mike,

Yes, please close the issue. Thanks for looking into the problem!

Best,
Dan
________________________________
