### ISSUE TITLE
Triggering

### ISSUE THREAD

**Issue by bulls54** [mcleung/PyAPT#7]
This wrapper is great! Thanks for taking the time to do this. 

I have one concern though. In my project, I am using a NI-DAQ to scan over a target. My plan is to use this motor control to move the target while I scan. Therefore, I need some sort of trigger. I saw the command MOT_SET_TRIGGER in the manual. I tried to load this command and noticed that it was not in the PyAPT.py file. So i figured I could add it and that did not work either. I opened up the APT.lib and the command was not even in the the .lib file. 

Is there something I am missing here? I figured that the APT files would have all the command from the Thorlabs APT Controllers manual. If this is not possible, do you have any suggestions on how I can sync the start of the motor with the start of the scanning? 

Thanks again for making this and I hope to hear from you soon!

**Comment by mcleu** [comment]
I would check with Thorlabs to see if they have a newer/more recent dll.

An alternative (that I would not recommend) would be to implement your own (it's just serial communication with the motor)

**Comment by mcleu** [comment]
@bulls54 Please let me know if you have any questions or updates, otherwise I will close the Issue.
Did Thorlabs provide a new DLL.
If so, can you please push it to this repo?
