### ISSUE TITLE
Use in MATLAB

### ISSUE THREAD

**Issue by nonohuff** [mcleung/PyAPT#8]
I am trying to interface with a MFF 101/102 Motorized flipper in MATLAB 2015bx32, and I was wondering where the header file for this library is and if you have a 32-bit version of the library.

I am a novice coder, so please excuse any ignorance in the above question. That being said, I would also love any suggestions you might have. All I need to do is get the motor to change positions.

**Comment by mcleu** [comment]
This is a python tool; not MATLAB.
I suggest you start your search by contacting Thorlabs.
In my experience, they have always been very helpful.
